require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
RSpec/MultipleExpectations:
  Max: 2
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 35
Metrics/BlockLength:
  Max: 30
Layout/LineLength:
  Max: 130
Style/GlobalVars:
  AllowedVariables: [$current_api_v1_user]
