name: danger
on: [pull_request]
permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  statuses: write
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup danger
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - run: gem install danger
      - name: Run danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget https://raw.githubusercontent.com/happiness-chain/danger/main/Dangerfile
          danger --verbose
